sudo: required
language: node_js
node_js:
- stable
- node
- 10
- 8
before_install:
# Update to the latest version as peer dependencies may cause issues otherwise
- npm install npm -g
script:
- npm run build
notifications:
  email:
    on_failure: change

jobs:
  include:
    - stage: deploy to npmjs
      node_js: 10
      deploy:
        skip_cleanup: true
        provider: npm
        email: $NPM_PUBLISH_USER
        api_key: $NPM_PUBLISH_TOKEN
        on:
          branch: master
          tags: true
